ARDUINO_DIR   = /usr/share/arduino
BOARD_TAG     = mega
BOARD_SUB     = atmega2560
MONITOR_PORT  = /dev/ttyACM1
MONITOR_BAUDRATE = 115200
ARDUINO_LIBS  = WiFi SPI

include $(HOME)/Code/Arduino-Makefile/Arduino.mk